name: todos
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.0-182.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  riverpod: ^1.0.3
  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
